### ISSUE TITLE
视频暂停时增加希望可配置弹幕继续播放的能力

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee-plugin-danmu#1]
如标题，在直播场景下会有类似需求，希望能够后续支持一下。
以及目前弹幕还有一个问题在于，切换tab之后，弹幕会被暂定，导致返回tab的时候弹幕一口气全部发出来，量级大了的时候会直接造成浏览器假死状态

**Comment by yandeqiang** [comment]
已经增加 updateByVideo 字段， 来配置，是否随video 的状态，播放暂停。

**Comment by yandeqiang** [comment]
1. 因为业务的场景比较多， sendMsg 的时机交由业务开管理。 这样业务在 sendMsg 的时候，可以做一层过滤。

2. 弹幕这一层， 会对同一时刻的弹幕数量做一定的限制（不过还没想好设置多少合适）。

这两个方式来防止某一个时刻数量过大的问题
